version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD
      - run:
         name: "Build docker images to docker hub"
         command:
          cp Dockerfile.production Dockerfile
          docker build -t issarapong/example-nodejs-express
          docker build -t issarapong/example-nodejs-express:${CIRCLE_SHA1}
          docker push issarapong/example-nodejs-express
          docker push issarapong/example-nodejs-express:${CIRCLE_SHA1}
      - run: echo Done